swagger: "2.0"
info:
  description: "descripcion"
  version: "0.0.1"
  title: "Taller"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "demo@demo.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/"
tags:
- name: "taller"
  description: "Demo swagger"
schemes:
- "http"
paths:
  /test/{testId}:
    post:
      tags:
      - "demo"
      summary: "solicitud"
      description: ""
      operationId: "post success"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: testId
        required: true
        type: integer
        minimum: 1
        description: The ID of the user to return.
      - in: "body"
        name: "body"
        description: "Datos generales"
        required: true
        schema:
          $ref: "#/definitions/DatosGenerales"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Respuesta"
          examples:
            response:
              success: true
        204:
          description: "NOT CONTENT"
        
        400:
          description: BAD REQUEST
          schema:
            $ref: '#/definitions/Errores'
          examples:
            response:
              errors:
                - code: 400
                  message: Datos de consulta incorrecto.
    put: 
      tags:
      - "demo"
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      parameters:
      - in: path
        name: testId
        required: true
        type: integer
        minimum: 1
        description: The ID of the user to return.
      - in: "body"
        name: "body"
        description: "Datos generales"
        required: true
        schema:
          $ref: "#/definitions/DatosGenerales"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/RespuestaPut"
          examples:
            response:
              success: true
        204:
          description: "NOT CONTENT"
        
        400:
          description: BAD REQUEST
          schema:
            $ref: '#/definitions/Errores'
          examples:
            response:
              errors:
                - code: 400
                  message: Datos de consulta incorrecto.
    delete: 
      tags:
      - "demo"
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      parameters:
      - in: path
        name: testId
        required: true
        type: integer
        minimum: 1
        description: The ID of the user to return.
      - in: "body"
        name: "body"
        description: "Datos generales"
        required: true
        schema:
          $ref: "#/definitions/DatosGenerales"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/RespuestaDelete"
          examples:
            response:
              success: true
        204:
          description: "NOT CONTENT"
        
        400:
          description: BAD REQUEST
          schema:
            $ref: '#/definitions/Errores'
          examples:
            response:
              errors:
                - code: 400
                  message: Datos de consulta incorrecto.
  /test:
    get: 
      tags:
      - "demo"
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Respuesta"
          examples:
            response:
              success: true
        204:
          description: "NOT CONTENT"
        
        400:
          description: BAD REQUEST
          schema:
            $ref: '#/definitions/Errores'
          examples:
            response:
              errors:
                - code: 400
                  message: Datos de consulta incorrecto.
  /test2:
    get:
      tags:
      - "demo"
      summary: "solicitud"
      description: ""
      operationId: "post success"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Datos generales"
        required: true
        schema:
          $ref: "#/definitions/DatosGenerales"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Respuesta"
          examples:
            response:
              success: true
        204:
          description: "NOT CONTENT"
        
        400:
          description: BAD REQUEST
          schema:
            $ref: '#/definitions/Errores'
          examples:
            response:
              errors:
                - code: 400
                  message: Datos de consulta incorrecto.
  /testNava:
    post:
      tags:
      - "demo"
      summary: "solicitud"
      description: ""
      operationId: "post success"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Datos generales"
        required: true
        schema:
          $ref: "#/definitions/DatosGeneralesNava"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/RespuestaNava"
          examples:
            response:
              success: true
        204:
          description: "NOT CONTENT"
        400:
          description: BAD REQUEST
          schema:
            $ref: '#/definitions/Errores'
          examples:
            response:
              errors:
                - code: 400
                  message: Datos de consulta incorrecto.
definitions:
  Errores:
    type: object
    description: 'Si existen errores, se listarán.'
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Error'
    title: Errores

  Error:
    type: object
    properties:
      code:
        type: string
        example: 404
        description: Código de error.
      message:
        type: string
        example: Título de error, El campo "campo" es requerido.
        description: Mensaje de error.
    title: Error
    description: error
  
  Respuesta:
    type: object
    properties:
      success:
        type: boolean
        description: Solicitud exitosa
      message:
        type: boolean
        description: La persona se agregó correctamente
  RespuestaPut:
    type: object
    properties:
      success:
        type: boolean
        description: Solicitud exitosa
      message:
        type: boolean
        description: La persona se actualizo correctamente

  RespuestaNava:
    type: object
    properties:
      success:
        type: boolean
        description: Solicitud exitosa
  
  RespuestaDelete:
    type: object
    properties:
      success:
        type: boolean
        description: Solicitud exitosa
      message:
        type: boolean
        description: La persona se borró correctamente
  
   
  DatosGenerales:
    type: "object"
    required:
    - "nombre"
    - "apellidoPaterno"
    properties:
      nombre:
        type: "string"
        example: "Daniel"
      apellidoPaterno:
        type: "string"
        example: Ramon
      apellidoMaterno:
        type: "string"
        example: Zapata
    example:
      nombre: Pedro
      apellidoPaterno: Juarez


  DatosGeneralesNava:
    type: "object"
    required:
    - "usuario"
    - "contraseña"
    properties:
      usuario:
        type: "string"
        example: "Daniel"
      contraseña:
        type: "string"
        example: Ramon
    example:
      nombre: Manava
      contraseña: 1234
      
